name: PHP Tests

on:
  push:
    branches:
    - v0.x 
  pull_request:
    branches:
    - v0.x

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Install dependencies
        run: composer install
      - name: Run Tests
        run: composer test
